resources:
- deployment.yaml

images:
- name: compliance-operator
  newName: ghcr.io/complianceascode/compliance-operator
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
