resources:
- deployment.yaml

images:
- name: compliance-operator
  newName: image-registry.openshift-image-registry.svc:5000/openshift/compliance-operator
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
