apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-operator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes  # We need to list the nodes to be able to selectively scan
      - namespaces # We need this to get the range
    verbs:
      - list
      - watch
  - apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - machineconfigs  # The compliance remediation controller operates on MachineConfigs
      - machineconfigpools
      - kubeletconfigs
    verbs:
      - list
      - get
      - patch
      - create
      - watch
      - update
      - delete
  - apiGroups:
      - compliance.openshift.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  # These are needed for remediating objects
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
      - oauths
    resourceNames:
      - cluster
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
  # Enforcement types
  - apiGroups:
      - templates.gatekeeper.sh
    resources:
      - constrainttemplates
    verbs:
      - list
      - get
      - patch
      - create
      - watch
      - update
      - delete
  - apiGroups:
      - config.gatekeeper.sh
    resources:
      - configs
    verbs:
      - list
      - get
      - patch
      - create
      - watch
      - update
      - delete
  - apiGroups:
      - constraints.gatekeeper.sh
    resources:
      - "*"
    verbs:
      - list
      - get
      - patch
      - create
      - watch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch
