# deploy variant
# Adds namespace to all resources.
namespace: openshift-compliance

bases:
- ../rbac
- ../manager
- ../ns

patches:
- path: manager_patch.yaml
  target:
    kind: Deployment
    name: compliance-operator