apiVersion: compliance.openshift.io/v1alpha1
kind: CustomRule
metadata:
  name: enable-nonroot-feature-gate-cel
  namespace: openshift-compliance
spec:
  checkType: Platform
  instructions: |-
    Verify that the nonRoot feature gate is enabled for the hyperconverged resource.

    Audit:
      Run the following command:
      $ oc get hyperconverged kubevirt-hyperconverged -n openshift-cnv -o jsonpath='{.spec.featureGates.nonRoot}'
      The output should be "true".

    Remediation:
      Enable nonRoot by setting its value to True.
  rationale: >
    Running workloads as root can lead to privilege escalation and unauthorized administrative
    access. Enabling the nonRoot feature gate ensures that KubeVirt workloads run with only the
    minimal privileges required, thereby reducing the risk of unintended or malicious privilege escalation.
  title: Ensure nonRoot Feature Gate is Enabled
  scannerType: CEL
  id: enable_nonroot_feature_gate_cel
  description: >
    Ensure that the hyperconverged resource (kubevirt-hyperconverged in the openshift-cnv namespace)
    has the nonRoot feature gate enabled. By default, KubeVirt workloads run in nonRoot mode.
  severity: high
  expression: >
    hco.spec.featureGates.nonRoot == true
  inputs:
    - kubeResource:
        name: hco
        apiGroup: hco.kubevirt.io
        version: v1beta1
        # The "resource" field below includes the object name (kubevirt-hyperconverged)
        # in the format "resourceName/objectName" to target the specific instance.
        resource: hyperconverged/kubevirt-hyperconverged
        namespace: openshift-cnv
  errorMessage: "The nonRoot feature gate is not enabled for the hyperconverged resource."
