---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-resource-collector
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - compliance.openshift.io
    resources:
      - compliancescans
    verbs:
      - get
