---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-resource-collector
subjects:
  - kind: ServiceAccount
    name: api-resource-collector
roleRef:
  kind: Role
  name: api-resource-collector
  apiGroup: rbac.authorization.k8s.io
