# permissions for end users to view complianceremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: complianceremediation-viewer-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations/status
  verbs:
  - get
