# permissions for end users to edit compliancescans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliancescan-editor-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancescans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancescans/status
  verbs:
  - get
