---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remediation-aggregator
subjects:
  - kind: ServiceAccount
    name: remediation-aggregator
    namespace: openshift-compliance
roleRef:
  kind: ClusterRole
  name: remediation-aggregator
  apiGroup: rbac.authorization.k8s.io
