---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rerunner
subjects:
  - kind: ServiceAccount
    name: rerunner
    namespace: openshift-compliance
roleRef:
  kind: Role
  name: rerunner
  apiGroup: rbac.authorization.k8s.io
