---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resultserver
subjects:
  - kind: ServiceAccount
    name: resultserver
    namespace: openshift-compliance
roleRef:
  kind: Role
  name: resultserver
  apiGroup: rbac.authorization.k8s.io
