---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resultscollector
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - compliance.openshift.io
    resources:
      - compliancescans
    verbs:
      - get
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
