# permissions for end users to view scansettingbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scansettingbinding-viewer-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings/status
  verbs:
  - get
