# permissions for end users to view tailoredprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailoredprofile-viewer-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - tailoredprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - tailoredprofiles/status
  verbs:
  - get
